FHIR Retry Logic
drajer-health/eCRNow pull request #373
Opened 2022-08-22 13:00 UTC by sabirnits15

2022-08-25 11:24 UTC, sabirnits15 commented on src/main/java/com/drajer/ecrapp/config/SpringConfiguration.java
> +    retryableExceptions.put(HttpServerErrorException.class, true);
Added

2022-08-25 11:26 UTC, sabirnits15 commented on src/main/java/com/drajer/sof/utils/FhirContextInitializer.java
> +      return new EcrFhirRetryClient(client, retryTemplate, requestId);
Yes, Changes incorporated

2022-08-25 11:27 UTC, sabirnits15 commented on src/main/java/com/drajer/ecrapp/fhir/utils/ecrretry/EcrFhirRetryClient.java
> +    return new EcrFhirRetryableRead(client.read(), this);
Added.

2022-09-12 06:45 UTC, AnanthaKrishnaV approved these changes

2022-09-12 06:45 UTC, AnanthaKrishnaV commented on src/main/java/com/drajer/ecrapp/fhir/utils/ecrretry/EcrFhirRetryablePage.java
> +              logger.info("Retry FHIR page");
Can you add the details like the URL is been retried and the current retry count in the log message. Same for all other classes.

2022-09-12 06:45 UTC, AnanthaKrishnaV commented on src/test/java/com/drajer/test/ITPageRetry.java
> +                "/FHIR/Observation?patient=12742571&category=laboratory&-pageContext=10065315_11316911_12742571_1_1&-pageDirection=NEXT")));
Maybe you can validate like below to avoid occasional failures. Same for other tests.
```suggestion
    wireMockServer.verify(
        moreThanOrExactly(15),
        getRequestedFor(
            urlEqualTo(
                "/FHIR/Observation?patient=12742571&category=laboratory&-pageContext=10065315_11316911_12742571_1_1&-pageDirection=NEXT")));
```

2022-09-21 10:59 UTC, AnanthaKrishnaV requested changes

2022-09-21 10:59 UTC, AnanthaKrishnaV commented on src/main/resources/application.properties
> +ecr.fhir.retry.maxRetryCount=5
By default set it to 3.

2022-09-21 11:10 UTC, AnanthaKrishnaV approved these changes

2022-11-08 15:56 UTC, merged